### ISSUE TITLE
Setting session expiry based on access token expiry is problematic

### ISSUE THREAD

**Issue by toolness** [18F/cg-django-uaa#22]
When we first implemented cloud.gov UAA in https://github.com/18F/calc/pull/317, we set the user's session expiry to that of the cloud.gov access token expiry:

> At present, we set the user's session expiry to the expiry of the access token we receive from cloud.gov. Given that the access tokens cloud.gov provides currently seem to have a lifetime of about 12 hours, this means that user sessions won't last long. If this ends up being a significant hassle, we can add code to automatically refresh the token later (even though we don't actually use the token to access any protected resources, it's important to refresh it as a way of ensuring that the user's account is still valid, e.g. that they haven't left GSA or something).

Unfortunately, when I first factored the code out into cg-django-uaa, it had been so long since I originally wrote it that I completely forgot about this limitation, and thus forgot to document it or implement a fix.

Currently, FEC is using this package and the incredibly short session expiry _is_ indeed an issue, so we need to figure out a way around this.

One quick stopgap fix may be to subclass `UaaBackend` like so:

```python
from uaa_client.authentication import UaaBackend

class MyUaaBackend(UaaBackend):
    def authenticate(self, uaa_oauth2_code=None, request=None, **kwargs):
        original_expiry = request.session.get_expiry_age()
        result = super().authenticate(
            uaa_oauth2_code=uaa_oauth2_code,
            request=request,
            **kwargs
        )
        if result is not None:
            # "Undo" the session expiry change just made by our superclass method.
            request.session.set_expiry(original_expiry)
        return result
```

This backend would then need to be specified in `settings.AUTHENTICATION_BACKENDS` instead of `uaa_client.authentication.UaaBackend`.

It should be noted, though, that this does have the security implications mentioned above, i.e. someone could log into the website, leave their employment with the government, yet still have access to the site for the next 2 weeks (or however long `SESSION_COOKIE_AGE` has been set to). So ideally we should add functionality to cg-django-uaa that auto-renews the access token whenever it expires, ensuring that the end user *does* get logged out soon if they lose access to cloud.gov.

**Comment by toolness** [comment]
Another alternative I considered was to add a new setting called `UAA_SET_SESSION_EXPIRY` which would default to `True` but could be overridden in `settings.py`.  However, I'm not sure if that's a great idea from a security standpoint, and I'd prefer to not promulgate more settings if at all possible.

**Comment by ccostino** [comment]
Thank you, @toolness!  I think your approach makes sense and the alternative does as well but I understand what you're getting at with the security and settings concerns.

For the record, the cloud.gov expiry is configured here:  https://github.com/18F/cg-deploy-cf/blob/master/cf-properties.yml#L321

And per some details surrounding [the documentation](https://cloud.gov/docs/apps/leveraging-authentication/) shared by Britta with us (which she mentioned might require an update to reflect this):

>Our AC-11 says "The Client UAA Server terminates sessions after 15 minutes of inactivity." because our requirement is "Prevents further access to the system by initiating a session lock after [FedRAMP Assignment: fifteen minutes] of inactivity or upon receiving a request from a user"

**Comment by LinuxBozo** [comment]
Ideally, you'd keep the session at the auth token expiration and when the session reaches expiration (or close), request a new access token with the refresh token, and if valid, re-up the session. So, then the session really becomes invalid when either you fail to get a new access token, or the refresh token has expired.  Without doing this, you could run into an issue where the user does not actually have a valid account but their session is still active because you are either using a fake expiration, or the longer refresh token validity.

`requests-oauthlib` has a decent enough writeup of the flow, and might be something to look into leveraging here: http://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#refreshing-tokens

**Comment by toolness** [comment]
Thanks @LinuxBozo !  I've started a WIP PR at #24; while I'm not setting the session expiration at the auth token expiration, I *am* ensuring that if the auth token can't be refreshed after it expires, the user is logged out.  More details at #24, feedback is welcome!
