### ISSUE TITLE
Add support for Django 2.2

### ISSUE THREAD

**Issue by Jkrzy** [18F/cg-django-uaa#48]
Lets add support for the new LTS version of Django, 2.2.

**Comment by tbaxter-18f** [comment]
The ci config appears to be specifying 1.10, the old LTS

**Comment by tbaxter-18f** [comment]
Might be a good time to look at https://github.com/18F/cg-django-uaa/issues/40 too. I don't want us to break this thing for anyone who hasn't updated to Django 2.x

**Comment by tbaxter-18f** [comment]
From discussions in Slack, we've determined the best path is to align the circle config and setup.py on Django 2.2, update the VERSION to 2.0 and update docs to reflect that anyone wanting still using Django 1.x should use the 1.3.x version.
